namespace Cakra.Modules.Post.Domain;

/// <summary>
/// Identifies whether a <see cref="Post"/> was authored by a human actor or generated by the system
/// (Post Domain §5; Architecture §12).
/// </summary>
public enum PostSource
{
    /// <summary>Intentionally authored by an organizational Person.</summary>
    HumanAuthored = 0,

    /// <summary>Automatically generated by the system in response to an operational event or state change.</summary>
    SystemGenerated = 1
}

/// <summary>
/// Canonical string representations and conversion helpers for <see cref="PostSource"/>.
/// </summary>
public static class PostSourceNames
{
    public const string HumanAuthored = "HUMAN_AUTHORED";
    public const string SystemGenerated = "SYSTEM_GENERATED";

    public static string ToName(this PostSource source) => source switch
    {
        PostSource.HumanAuthored => HumanAuthored,
        PostSource.SystemGenerated => SystemGenerated,
        _ => throw new ArgumentOutOfRangeException(nameof(source), source, $"Unsupported PostSource '{source}'.")
    };

    public static PostSource FromName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            throw new ArgumentException("Post source name cannot be null or empty.", nameof(name));
        }

        return name.Trim().ToUpperInvariant() switch
        {
            HumanAuthored => PostSource.HumanAuthored,
            SystemGenerated => PostSource.SystemGenerated,
            _ => throw new ArgumentException($"Unsupported Post source '{name}'.", nameof(name))
        };
    }
}
